language: node_js

dist: xenial

os: linux

node_js:
  - v10.8.0

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: always

services:
  - docker

before_install:
  - docker run -p 8000:8000 amazon/dynamodb-local &
  - echo "[default]" >> $HOME/.aws/credentials
  - echo "aws_access_key_id = accessKey" >> $HOME/.aws/credentials
  - echo "aws_secret_access_key = aws_secret_access_key" >> $HOME/.aws/credentials
  - export AWS_SDK_LOAD_CONFIG=1
  - export AWS_SHARED_CREDENTIALS_FILE=$HOME/.aws/credentials
  - sleep 60
  - sudo chmod +x travis.sh
  - ./travis.sh

script:
  - npm install
  - npm run lint
  - npm run build
  - npm run codeCoverage
  - npm link
  - npm tst
